#!/bin/bash
while [ 1==1 ]
do
        filename=$(date '+%Y-%m-%d %H:%M:%S')
        echo "-------------------------------------------------- $filename"
        ls -lR ./logs
        sleep 0.5s
done

1.时钟同步
2.文件授权
3.延时投递
4.先移动文件后重命名
